DROP TABLE IF EXISTS CLIENTE, PACOTE, DESTINO, ATIVIDADE, CLIENTE_COMPRA_PACOTE;

CREATE TABLE CLIENTE (
	COD_CLIENTE SERIAL PRIMARY KEY,
	CPF VARCHAR(11) UNIQUE,
	NOME VARCHAR(100)
);

CREATE TABLE PACOTE (
	COD_PACOTE SERIAL PRIMARY KEY,
	DATA_SAIDA DATE,
	DIAS INT,
	NOME VARCHAR(50),
	PRECO DECIMAL(10,2)
);

CREATE TABLE DESTINO (
	COD_DESTINO SERIAL PRIMARY KEY,
	CIDADE VARCHAR(50),
	PAIS VARCHAR(30)
);

CREATE TABLE ATIVIDADE (
	COD_ATIVIDADE SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(200),
	DERACAO INT,
	PUBLIC_ALVO VARCHAR(30),
	FK_COD_DESTINO INT,
	FOREIGN KEY (FK_COD_DESTINO) REFERENCES DESTINO(COD_DESTINO)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CLIENTE_COMPRA_PACOTE (
	COD_COMPRA SERIAL PRIMARY KEY,
	DATA DATE,
	VALOR DECIMAL(10,2),
	FK_COD_PACOTE INT,
	FK_COD_CLIENTE INT,
	FOREIGN KEY (FK_COD_PACOTE) REFERENCES PACOTE(COD_PACOTE)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (FK_COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
		ON DELETE CASCADE ON UPDATE CASCADE
);

